import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider.tsx";
import NavBar from "@/components/NavBar";

const inter = Space_Grotesk({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
    
      <body className={`${inter.className}`}>
      <ThemeProvider
      attribute="class"
      defaultTheme="dark"
      enableSystem
      disableTransitionOnChange
      >	<main className="flex flex-col max-w-7xl mx-auto min-h-screen space-y-10 p-5 ">
      <NavBar/>
      <div className="w-full flex-1 ">{children}</div>
      
    </main>
      </ThemeProvider>
       
        </body>
     
     
    </html>
  );
}
